- README.md
- packages/update-spec/README.md
- packages/update-spec/action.yml
- packages/update-spec/dist/index.js
- packages/update-spec/index.ts
- packages/update-spec/package-lock.json
- packages/update-spec/package.json
- packages/update-spec/tsconfig.json
Экшн для обновления спецификаций в sdk
> Update spec action

- packages/get-deployment-stages/package-lock.json
- packages/get-deployment-stages/package.json
- packages/get-deployment-stages/src/events/repository_dispatch.ts
Мелочь, просто чтобы убрать лишний `any`.
> chore: upgrade `@octokit/webhooks` to latest version

- packages/bump-version/dist/index.js
- packages/bump-version/index.ts
Поменял две строчки, пелл реквест на +8,913 −8,877 😀
> fix(bump-version): push only latest tag

- packages/update-spec/index.ts
Добавил получение доков от сервиса scrooge
> add scrooge docs to sdk

- packages/update-spec/index.ts
https://reallyosome.atlassian.net/browse/IN-89
- Pablo: https://github.com/OsomePteLtd/pablo/pull/402 
- SDK: https://github.com/OsomePteLtd/sdk/pull/22 
- **Actions: https://github.com/OsomePteLtd/actions/pull/55**
> IN-89: Move Pablo Spec to SDK

- packages/update-spec/dist/index.js
- packages/update-spec/index.ts
https://reallyosome.atlassian.net/browse/IN-97
- Hero: https://github.com/OsomePteLtd/hero/pull/519
- SDK: https://github.com/OsomePteLtd/sdk/pull/30
- **Actions: https://github.com/OsomePteLtd/actions/pull/61**
> IN-97: Move Hero Spec to SDK

- packages/update-spec/dist/index.js
- packages/update-spec/index.ts
https://reallyosome.atlassian.net/browse/IN-100
- Scrooge: https://github.com/OsomePteLtd/scrooge/pull/41
- SDK: https://github.com/OsomePteLtd/sdk/pull/35
- **Actions: https://github.com/OsomePteLtd/actions/pull/62**
> IN-100: Move Scrooge Spec to SDK

- packages/update-spec/dist/index.js
- packages/update-spec/index.ts
https://reallyosome.atlassian.net/browse/IN-99
- Billy: https://github.com/OsomePteLtd/billy/pull/131
- SDK: https://github.com/OsomePteLtd/sdk/pull/39
- **Actions: https://github.com/OsomePteLtd/actions/pull/63**
> IN-99: Move Billy Spec to SDK

- packages/update-spec/dist/index.js
- packages/update-spec/index.ts
https://reallyosome.atlassian.net/browse/IN-101
- Payot: https://github.com/OsomePteLtd/payot/pull/33
- SDK: https://github.com/OsomePteLtd/sdk/pull/45
- **Actions: https://github.com/OsomePteLtd/actions/pull/64**
> IN-101: Move Payot Spec to SDK

- packages/update-spec/dist/index.js
- packages/update-spec/index.ts
https://reallyosome.atlassian.net/browse/IN-119
- Pechkin: https://github.com/OsomePteLtd/pechkin/pull/19
- SDK: https://github.com/OsomePteLtd/sdk/pull/47
- **Actions: https://github.com/OsomePteLtd/actions/pull/65**
> IN-119: Move Pechkin Spec to SDK

- packages/update-spec/dist/index.js
- packages/update-spec/index.ts
https://reallyosome.atlassian.net/browse/IN-98
- Core: https://github.com/OsomePteLtd/core/pull/858
- SDK: https://github.com/OsomePteLtd/sdk/pull/52
- **Actions: https://github.com/OsomePteLtd/actions/pull/66**
> IN-98: Move Core Spec to SDK

- packages/bump-packages/action.yml
Add packages for bumping to bump-packages action
> Add packages for bumping

- packages/dependency-track-check/action.yml
Reverts OsomePteLtd/actions#233
> Revert "update dependency-track-check action"

- packages/bump-packages/action.yml
Reverts OsomePteLtd/actions#238
> Revert "update bump-packages workflow"

- packages/bump-packages/action.yml
Reverts OsomePteLtd/actions#237
> Revert "add check github-actor step"

- packages/bump-packages/action.yml
Reverts OsomePteLtd/actions#244
> Revert "Chore/update bump packages action"

- packages/bump-packages/action.yml
Reverts OsomePteLtd/actions#246
> Revert "update bump-packages action"

- packages/lokalise-download/action.yml
https://reallyosome.atlassian.net/jira/software/c/projects/PL/boards/80?modal=detail&selectedIssue=PL-2204
> PL-2204: Update lokalise download action

- packages/lokalise-download/action.yml
- packages/lokalise-download/download.sh
prevents replacing `\n` with `\\n`
> PL-2240 fix escaping new lines in PRs

- packages/e2e-websome/action.yml
Failed e2e: https://github.com/OsomePteLtd/roberto/actions/runs/10507656740/job/29110347902
Caused by recently added WL e2e test
> Fix e2e WL

- packages/e2e-websome/action.yml
Fix e2e runner: https://github.com/OsomePteLtd/roberto/actions/runs/10790730727/job/29926996669
> Bump artifact v4

- packages/bump-packages/action.yml
Relates with https://github.com/OsomePteLtd/core/pull/10120
> Return "server-toolkit" to "bump"

- packages/fail-on-code-and-migrations/action.yml
This reverts commit 7390b04254336062452a8d6fe5ff0c249c985aed.
> Revert "security issue" since the source repo was restored
